-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE requests (
    id serial PRIMARY KEY,
    username text NOT NULL,
    userid integer NOT NULL,
    description text NOT NULL,
    askedat TIMESTAMP DEFAULT now(),
    answerd TIMESTAMP
);

